variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - build

build-job:
  stage: build
  script:
    - rm -rf install/usr/bin/*
    - rm -rf debug/
    - make deploy
    - make debug-symbols
  artifacts:
    paths:
      - install
      - debug