stdout-rotate-size = "50 KB"
stdout-should-append-timestamp-to-filename = true

[restart]
strategy = "always"
backoff = "5s"
attempts = 3 

[environment]
#keep-env = false
additional = { RUST_LOG = "info,zenoh=off" , ZENOH_CONFIG = "/usr/etc/rccn_zenoh_config.json5" }