frames:
  spacecraft_id: 0xAB
  in:
    frame_kind: tc
    transport:
      kind: zenoh
      key_sub: zenoh/serial/in
  out:
    frame_kind: uslp
    transport:
      kind: zenoh
      key_pub: zenoh/serial/out


virtual_channels:
  - id: 0
    name: bus_realtime
    splitter: space_packet
    tx_transport:
      kind: zenoh
      key_pub: vc/bus_realtime/rx
    rx_transport:
      kind: zenoh
      key_sub: vc/bus_realtime/tx
  - id: 1
    name: cfdp
    tx_transport:
      kind: zenoh
      key_pub: vc/cfdp/rx
    rx_transport:
      kind: zenoh
      key_sub: vc/cfdp/tx
